name: .NET-Develop-Build

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
    
env:
  HOST: ${{secrets.HOST}}
  DATABASE_TEST: ${{secrets.DATABASE_TEST}}
  USER_NAME: ${{secrets.USER_NAME}}
  PASSWORD_DB: ${{secrets.PASSWORD_DB}}
  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: mirromutth/mysql-action@v1.1
      with:
        mysql version: '5.6.50' # Optional, default value is "latest". The version of the MySQL
        mysql database: $DATABASE_TEST # Optional, default value is "test". The specified database which will be create
        mysql host: $HOST
        mysql root password: $PASSWORD_DB # Required if "mysql user" is empty, default is empty. The root superuser password
        mysql user: $USER_NAME # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
        mysql password: $PASSWORD_DB # Required if "mysql user" exists. The password for the "mysql user"

    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
     
      
